services:
  user-management-service:
    build: ./
    container_name: user-management-service
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-management-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - microservices-network
    depends_on:
      - user-management-db

  user-management-db:
    image: postgres:latest
    container_name: user-management-db
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

