spring.application.name=user-management-service
server.port=8086

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=30000

# DATABASE DOCKER
spring.datasource.url=jdbc:postgresql://DB-user-management:5432/userdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
