spring.application.name=user-management-service
server.port=8086

#logging.level.root=DEBUG

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

